apiVersion: v1
kind: Pod
metadata:
  name: k8-with-node # This field specifies the name of the Pod, which is k8-with-node. The name is used to uniquely identify the Pod within the Kubernetes cluster.
  labels: #Labels are key-value pairs attached to objects in Kubernetes. They are used to identify and select objects. hese labels can be used for various purposes such as selecting Pods for deployment, grouping Pods for monitoring, etc.
    app: k8-with-node
spec:
  containers:
    - name: k8-with-node #This specifies the name of the container. In this example, it's named k8-with-node
      image: naveta/k8-with-node:v2
      ports:
        - containerPort: 5000
  imagePullSecrets:
    - name: k8-registry-secret
