apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8-with-node-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 1
