# Define the PodDisruptionBudget resource
---
# Specify the API version and resource kind
apiVersion: policy/v1
kind: PodDisruptionBudget

# Metadata for the PodDisruptionBudget resource
metadata:
  # Name of the PodDisruptionBudget, using Helm template for fullname
  name: {{ template "k8-day-5.fullname" . }}-pdb
  # Namespace where the PodDisruptionBudget is created
  namespace: {{ .Release.Namespace }}
  # Labels for the PodDisruptionBudget
  labels:

# Specifications for the PodDisruptionBudget
spec:
  # Conditionally include minAvailable field if defined in values.yaml
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}

  # Conditionally include maxUnavailable field if defined in values.yaml
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}

  # Selector to match labels of the pods to which this PDB applies
  selector:
    matchLabels:
      # Match label "app.kubernetes.io/name" with the Helm fullname
      app.kubernetes.io/name: {{ include "k8-day-5.fullname" . }}
