apiVersion: v1
kind: Service
metadata:
  name: wordpress # Name of the service
  labels:
    app: wordpress # Label for identifying this service
spec:
  type: NodePort # Type of the service (NodePort, ClusterIP, etc.)
  ports:
  - port: 80 # Port on which the service is exposed
    targetPort: 80 # Port on which the pods are listening
    nodePort: 30080 # Port on which the service is accessible from outside the cluster
  selector:
    app: wordpress # Selector to route traffic to pods with matching labels
