apiVersion: v1
kind: Service
metadata:
  name: {{ include "day-6-flux-helm-release.fullname" . }}
  labels:
    {{- include "day-6-flux-helm-release.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "day-6-flux-helm-release.selectorLabels" . | nindent 4 }}
